// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"etfMicros/internal/biz"
	"etfMicros/internal/conf"
	"etfMicros/internal/data"
	"etfMicros/internal/server"
	"etfMicros/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	etfRepo := data.NewEtfRepo(dataData, logger)
	etfUseCase := biz.NewEtfUseCase(etfRepo, logger)
	etfService := service.NewEtfService(etfUseCase)
	grpcServer := server.NewGRPCServer(confServer, etfService, logger)
	httpServer := server.NewHTTPServer(confServer, etfService, logger)
	registrar := server.NewRegistrar()
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
